POST http://localhost:3333/courses
Content-Type: application/json

{
    "title":"Curso de React Native"
}

###
GET http://localhost:3333/courses


###
GET http://localhost:3333/courses/a565ed5c-cea7-41be-abbd-a92d608630bd