POST http://localhost:3333/courses
Content-Type: application/json

{
    "title":"Curso de Banco de dados"
}

###
# GET http://localhost:3333/courses
# GET http://localhost:3333/courses?search=react
 GET http://localhost:3333/courses?orderBy=title
# GET http://localhost:3333/courses?orderBy=title&page=1


###
GET http://localhost:3333/courses/a565ed5c-cea7-41be-abbd-a92d608630bd